// This file was generated by Convex.
// Do not modify it manually!

import type { FunctionReference } from "convex/server";

export const api = {
  rka: {
    searchAndFilter: {
      args: {
        filters: {
          searchQuery: "string | undefined",
          status: "string | undefined",
          fiscalYear: "string | undefined",
          createdBy: "Id<\"users\"> | undefined",
        } | undefined,
        pagination: {
          page: "number",
          limit: "number",
        },
      },
      returns: {
        documents: "any[]",
        pagination: {
          page: "number",
          limit: "number",
          totalItems: "number",
          totalPages: "number",
        },
      },
    },
    getFiscalYears: {
      args: {},
      returns: "string[]",
    },
  },
};
